version: '3'

services:
  dbos:
    image: mysql:5.7
    volumes:
      - mysql_new_storage:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: redhatroot
      MYSQL_USER: root
      MYSQL_PASSWORD: redhat
      MYSQL_DATABASE: mydb

  wordpressos:
    image: wordpress:5.1.1-php7.3-apache
    volumes:
      - wp_new_storage:/var/www/html
    restart: always
    depends_on: 
        - dbos
    ports: 
      - 8081:80
    environment: 
      WORDPRESS_DB_HOST: dbos
      WORDPRESS_DB_USER: manish
      WORDPRESS_DB_PASSWORD: redhatroot
      WORDPRESS_DB_NAME: mydb

volumes:  
   wp_new_storage:
   mysql_new_storage:


